### ISSUE TITLE
Trying to fly 'hiccups' on 1.12.2 server.

### ISSUE THREAD

**Issue by ethanwittenberg** [Broulf/COF#3]
While double tapping space to fly, I have to try a couple times to get it to work, during that time I ascend slowly while my FOV goes in and out. Double tapping to turn off flight does the same thing, takes a couple tries, and you don't fall directly down how you would expect, but sort of glide down. Very odd. I'm not sure how you would reproduce. No one else on the server has the issue, nor does anything show up in any of the logs. Let me know if you want a mod list. Forge version 14.23.5.2847. [Here's a video.](https://streamable.com/1b15fv) Any help you could provide would be appreciated. Thanks

**Comment by Broulf** [comment]
I genuinely have no idea what could be causing this... I've seen this problem once before with Vanilla MC in Creative mode about a week ago, it was caused by using Barrier (Synergy fork) and using my main PC's mouse and keyboard on the Linux machine. Do you happen to have a program that's similar (i.e. Barrier, Synergy, Mouse w/o Borders, etc) and using it in the same fashion?

**Comment by ethanwittenberg** [comment]
I checked through my programs list and I don't, on top of that it works flawlessly in both single player with that set of mods and in multiplayer on a local server with just that and FTBUtils installed. It's got to be related to that specific server I am playing on, right, so why does it only bug up for me, and no one else. Very odd. Have the exact same install as the person it worked for so I am beyond perplexed.

**Comment by Broulf** [comment]
Hmm, okay try this, what version of the mod is on the server, and what version of the mod is in your client? There are two mod versions on Curseforge, V0.3 which was the original version of the mod with an older flight procedure, and the newer V2.1 which has a full rewrite of the flight procedure. They both contain the same mod_id so forge won't complain when updating mods. It might be that and I accidentally messed up the export of the newer version with the same version tags as the original, this would cause the forge server to read the new/older client version of the mods as the same version the server has and could be attempting to use the server flight class/procedure instead of the client based one.

**Comment by ethanwittenberg** [comment]
They are both listed as the same, 2.1 from the file name for the server, "CoinOfFlight+1.12.2-(2.1)" and 2.1.0 which for the client, which is what forge says in game.

**Comment by ethanwittenberg** [comment]
Figured it out. We're playing the Compact Claustrophobia modpack, the version included with that was 0.3 but creative mode flight is disabled unless you have the coin in your inventory, so we manually upgraded both to 2.1.0. My best guess is something in our mod list conflicted with the newer version. Appreciate your help! [Here's a link to the modpack,](https://www.curseforge.com/minecraft/modpacks/compact-claustrophobia/files/3035319) if you wanted to try to reproduce it, just replace 2.1.0 with 0.3, though I imagine its never happened before and won't happen again.
